baseURL = "https://hugo.skj.dev"
languageCode = "en-us"
paginate = 5
theme = "terminal"

[params]

  contentTypeName = "posts"

  themeColor = "green"

  showMenuItems = 5

  showLanguageSelector = false

  fullWidthTheme = false

  centerTheme = true

  showLastUpdated = false

[params.twitter]
  creator = "ttys0"

[languages]
  [languages.en]
    languageName = "English"
    title = "skj.dev"
    subtitle = "yet another tech blog"
    owner = "sean"
    copyright = "© 2020 Sean Johnson"
    menuMore = "Show More"
    readMore = "Read More"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "skj.dev"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
        weight = -10
      [[languages.en.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/ttyS0"
        weight = -9
      [[languages.en.menu.main]]
        identifier = "wiki"
        name = "wiki"
        url = "https://skj.wiki"
        weight = -8
      [[languages.en.menu.main]]
        identifier = "108minutes"
        name = "blog"
        url = "https://108minutes.net"
        weight = -7


